baseurl = "/"
languageCode = "en-us"
title = "Scribbled Notes"
theme = "hugo-theme-casper"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 5
canonifyurls = true

[params]
  description = "A tiny slice of the web for spewing the guts of my mind."
  cover = "images/IMG_1024.jpg"
  author = "Jackie"
  authorlocation = "UK"
  authorwebsite = "http://scribblednotes.net"
  bio= "Female, mid forties, geek, photography nut. Powered by tea."
  logo = "images/avatar@2x.jpg"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "scribblednotes"
  twitterName = "jackieplage"
  instagramName = "jackieplage2"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = "jackieplage"
